# Generated by Django 5.2.11 on 2026-02-20 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('unit', models.TextField()),
                ('price_release', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'catalog_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('section', 'Секция'), ('subsection', 'Подсекция'), ('group', 'Группа'), ('spec', 'Спецификация')], max_length=20)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'catalog_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'catalog_sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReverseEnglishAuction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_bid_decrement', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('auction_type', models.ForeignKey(limit_choices_to={'app_label': 'bidfall'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bidfall.auction')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidfall.catalogitem')),
            ],
            options={
                'db_table': 'auction_items',
                'unique_together': {('auction', 'catalog_item')},
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='catalog_items',
            field=models.ManyToManyField(related_name='auctions', through='bidfall.AuctionItem', to='bidfall.catalogitem'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidfall.auction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
