# Generated by Django 5.2.11 on 2026-03-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='catalog_item',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bidfall.catalogitem'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
