# Generated by Django 5.2.11 on 2026-03-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0002_alter_auctionitem_catalog_item_alter_bid_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='bidfall.bid'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_determined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Закупщик'), ('supplier', 'Поставщик'), ('admin', 'Администратор')], default='supplier', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
