# Generated by Django 5.2.11 on 2026-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0003_auction_winner_bid_auction_winner_determined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HELD', 'Held'), ('PENDING_LOSE', 'Pending Lose'), ('LOSE', 'Lose')], default='PENDING', max_length=20),
        ),
    ]
