# Generated by Django 5.2.11 on 2026-03-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0004_bid_payment_id_bid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HELD', 'Held'), ('LOSE', 'Lose'), ('WON', 'Won'), ('RELEASED', 'Released'), ('FORFEIT', 'Forfeit')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BID_PLACEMENT_HOLD', 'Bid Placement Hold'), ('BID_CONCURRENT_RELEASE', 'Bid Concurrent Release'), ('BID_LOSS_RELEASE', 'Bid Loss Release'), ('BID_WIN_SIGNED_RELEASE', 'Bid Win Signed Release'), ('BID_WIN_FORFEIT_CHARGE', 'Bid Win Forfeit Charge'), ('AUCTION_CREATION_HOLD', 'Auction Creation Hold'), ('AUCTION_SIGNED_RELEASE', 'Auction Signed Release'), ('AUCTION_FORFEIT_CHARGE', 'Auction Forfeit Charge')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('HELD', 'Held'), ('CHARGED', 'Charged')], default='PENDING', max_length=20)),
                ('payment_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfall.auction')),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfall.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
