# Generated by Django 5.2.11 on 2026-03-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0005_remove_bid_payment_id_alter_auction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfall.auction'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfall.bid'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_id',
            field=models.CharField(max_length=36),
        ),
        migrations.CreateModel(
            name='ConfirmationFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=8)),
                ('signing_deadline', models.DateTimeField()),
                ('creator_signed_at', models.DateTimeField(blank=True, null=True)),
                ('winner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_flow', to='bidfall.auction')),
            ],
        ),
    ]
