# Generated by Django 5.2.11 on 2026-04-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfall', '0006_alter_paymenttransaction_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='type',
            field=models.CharField(choices=[('BID_PLACEMENT_HOLD', 'Bid Placement Hold'), ('BID_CONCURRENT_RELEASE', 'Bid Concurrent Release'), ('BID_LOSS_RELEASE', 'Bid Loss Release'), ('BID_WIN_SIGNED_RELEASE', 'Bid Win Signed Release'), ('BID_WIN_FORFEIT_CHARGE', 'Bid Win Forfeit Charge'), ('AUCTION_CREATION_HOLD', 'Auction Creation Hold'), ('AUCTION_SIGNED_CHARGE', 'Auction Signed Charge'), ('AUCTION_NO_WINNERS_RELEASE', 'Auction No Winners Release'), ('AUCTION_FORFEIT_CHARGE', 'Auction Forfeit Charge')], max_length=32),
        ),
    ]
