# -*- coding: utf-8 -*-
from pathlib import Path


APP_PATH = Path("frontend/src/app_market_clean.tsx")
API_PATH = Path("frontend/src/api.ts")


REPLACEMENTS = [
    # Fix mojibake introduced earlier in helper maps
    ("Р§РµСЂРЅРѕРІРёРє", "Черновик"),
    ("РћРїСѓР±Р»РёРєРѕРІР°РЅ", "Опубликован"),
    ("РђРєС‚РёРІРµРЅ", "Активен"),
    ("Р—Р°РІРµСЂС€РµРЅ", "Завершен"),
    ("Р—Р°РєСЂС‹С‚", "Закрыт"),
    ("РћС‚РјРµРЅРµРЅ", "Отменен"),
    ("РџРѕСЃС‚Р°РІС‰РёРє", "Поставщик"),
    ("Р—Р°РєР°Р·С‡РёРє", "Заказчик"),
    ("РђРґРјРёРЅРёСЃС‚СЂР°С‚РѕСЂ", "Администратор"),
    ('"Р—Р°РІРµСЂС€РµРЅ"', '"Завершен"'),
    ("Рґ ${h % 24}С‡ РѕСЃС‚Р°Р»РѕСЃСЊ", "д ${h % 24}ч осталось"),
    ("С‡ ${m}Рј РѕСЃС‚Р°Р»РѕСЃСЊ", "ч ${m}м осталось"),
    # UI labels and messages
    (">Reverse<", ">Реверс<"),
    (">Listing<", ">Лот<"),
    ('"No description"', '"Нет описания"'),
    ('"Edit"', '"Редактировать"'),
    ("Failed to load auctions:", "Не удалось загрузить аукционы:"),
    ("Failed to load auction:", "Не удалось загрузить аукцион:"),
    ("Sign in to view bid history.", "Войдите, чтобы посмотреть историю ставок."),
    ("No bids yet.", "Ставок пока нет."),
    ("Sign in to check winner.", "Войдите, чтобы проверить победителя."),
    ("Signed in.", "Вход выполнен."),
    ("Sign in failed:", "Ошибка входа:"),
    ("Account created for ", "Аккаунт создан: "),
    ("Registration failed:", "Ошибка регистрации:"),
    ("Please sign in before creating an auction.", "Сначала войдите в аккаунт, чтобы создать аукцион."),
    ("Auction created.", "Аукцион создан."),
    ("Create failed:", "Ошибка создания:"),
    ("Please sign in before placing a bid.", "Сначала войдите в аккаунт, чтобы сделать ставку."),
    ("Bid submitted.", "Ставка отправлена."),
    ("Bid failed:", "Ошибка ставки:"),
    ("Please sign in first.", "Сначала войдите в аккаунт."),
    ("Account updated.", "Данные аккаунта обновлены."),
    ("Update failed:", "Ошибка обновления:"),
    ("Sign in first.", "Сначала войдите в аккаунт."),
    ("Auction published.", "Аукцион опубликован."),
    ("Draft saved.", "Черновик сохранен."),
    ('Close auction "${auction.title}"? This action changes status to CLOSED.', 'Закрыть аукцион "${auction.title}"? Статус будет изменен на CLOSED.'),
    ("Auction closed.", "Аукцион закрыт."),
    ("Close failed:", "Ошибка закрытия:"),
    (">Bidfall Market<", ">Bidfall Маркет<"),
    (">Live auctions<", ">Активные аукционы<"),
    ('placeholder="Search auctions by title, id or status"', 'placeholder="Поиск аукционов по названию, ID или статусу"'),
    (">Search<", ">Поиск<"),
    (">Home<", ">Главная<"),
    (">Auctions<", ">Аукционы<"),
    (">Create auction<", ">Создать аукцион<"),
    (">Account<", ">Аккаунт<"),
    (">Sign in<", ">Войти<"),
    ('title="Live auctions happening now"', 'title="Идущие сейчас аукционы"'),
    ('subtitle="Auctions running right now."', 'subtitle="Аукционы, которые идут прямо сейчас."'),
    (">View all<", ">Показать все<"),
    (">Loading auctions...<", ">Загрузка аукционов...<"),
    (">No active auctions right now.<", ">Сейчас нет активных аукционов.<"),
    ('title="Ending soon"', 'title="Скоро завершатся"'),
    ('subtitle="Quick access to auctions closing first."', 'subtitle="Быстрый доступ к аукционам, которые закроются первыми."'),
    (">No active auctions yet.<", ">Активных аукционов пока нет.<"),
    ('>{(a.status ?? "").replace(/_/g, " ")}<', ">{statusText(a.status)}<"),
    ('title="Filters"', 'title="Фильтры"'),
    ('subtitle="Marketplace-style listing controls."', 'subtitle="Параметры отображения списка аукционов."'),
    (">All<", ">Все<"),
    (">Live now<", ">Идут сейчас<"),
    (">Search<input", ">Поиск<input"),
    ('placeholder="Auction title, status, id"', 'placeholder="Название аукциона, статус, ID"'),
    (" listings</div>", " объявлений</div>"),
    ('title="Auction listings"', 'title="Список аукционов"'),
    ('subtitle="Browse all auctions in a marketplace layout."', 'subtitle="Просмотр всех аукционов в формате витрины."'),
    (">Refreshing...<", ">Обновление...<"),
    (">No auctions match your search.<", ">По вашему запросу ничего не найдено.<"),
    ('"Auction details"', '"Аукцион"'),
    ("`Live auction`", "`Активный аукцион`"),
    ('"Select an auction from listings."', '"Выберите аукцион из списка."'),
    ('"Loading auction..."', '"Загрузка аукциона..."'),
    ('"Auction not found."', '"Аукцион не найден."'),
    ('"No description provided."', '"Описание отсутствует."'),
    (">Current price<", ">Текущая цена<"),
    (">Start price<", ">Начальная цена<"),
    (">Ends in<", ">До окончания<"),
    (">Min step (decrease)<", ">Мин. шаг снижения<"),
    (">Starts: {", ">Начало: {"),
    (">Ends: {", ">Окончание: {"),
    (">Seller<", ">Продавец<"),
    (">Overview<", ">Обзор<"),
    (">Bids<", ">Ставки<"),
    (">Lots<", ">Лоты<"),
    ('"Item"', '"Позиция"'),
    ('"No lots attached yet."', '"Лоты пока не добавлены."'),
    ('"Loading bids..."', '"Загрузка ставок..."'),
    (">Supplier<", ">Поставщик<"),
    ('"No comment"', '"Без комментария"'),
    ('"Edit draft auction"', '"Редактирование черновика"'),
    ('"Only draft auctions can be edited. You can publish when ready."', '"Редактировать можно только черновики. Когда все готово, опубликуйте аукцион."'),
    ('"Place a bid"', '"Сделать ставку"'),
    ('"Submit a new reverse bid for this auction."', '"Отправьте новую ставку для этого аукциона."'),
    ('"Select an auction first."', '"Сначала выберите аукцион."'),
    (">Title<input", ">Название<input"),
    (">Start time<", ">Время начала<"),
    (">End time<", ">Время окончания<"),
    (">Min decrement<", ">Мин. шаг снижения<"),
    (">Description<textarea", ">Описание<textarea"),
    ('"Saving..."', '"Сохранение..."'),
    ('"Save draft"', '"Сохранить черновик"'),
    ('"Please wait..."', '"Подождите..."'),
    ('"Publish"', '"Опубликовать"'),
    ('"Close auction"', '"Закрыть аукцион"'),
    ('"This auction is already published. Owners cannot edit or bid on published auctions."', '"Этот аукцион уже опубликован. Владелец не может редактировать его или делать ставки."'),
    ('"Sign in as a supplier to place bids."', '"Войдите как поставщик, чтобы делать ставки."'),
    ('"Only supplier accounts can place bids in this auction."', '"Ставки в этом аукционе могут делать только поставщики."'),
    ('"Bidding opens when the auction becomes active."', '"Прием ставок начнется, когда аукцион станет активным."'),
    ('"Bid price (lower is better)"', '"Цена ставки (чем ниже, тем лучше)"'),
    ('placeholder="Enter a lower price"', 'placeholder="Введите более низкую цену"'),
    ('"Comment (optional)"', '"Комментарий (необязательно)"'),
    ('placeholder="Delivery time, notes"', 'placeholder="Срок поставки, примечания"'),
    ('"Sending..."', '"Отправка..."'),
    ('"Submit bid"', '"Отправить ставку"'),
    ('"Refresh bids"', '"Обновить ставки"'),
    ('"Check winner"', '"Проверить победителя"'),
    ('"Checking winner..."', '"Проверка победителя..."'),
    ("Current winner, ", "Текущий победитель, "),
    ('"Owner actions"', '"Действия владельца"'),
    ('"Manage your auction status."', '"Управление статусом аукциона."'),
    ('"More auctions"', '"Другие аукционы"'),
    ('"Open another live or recent auction."', '"Откройте другой активный или недавний аукцион."'),
    ('"No auctions available."', '"Нет доступных аукционов."'),
    ('"Create a reverse auction"', '"Создание обратного аукциона"'),
    ('"Create and publish a new auction"', '"Создайте и опубликуйте новый аукцион"'),
    ('"Sign in first, then return to this form. Your form data stays on this page."', '"Сначала войдите, затем вернитесь к форме. Данные формы останутся на странице."'),
    ('placeholder="Office supplies tender"', 'placeholder="Тендер на офисные товары"'),
    ('"Save mode"', '"Режим сохранения"'),
    (">Draft<", ">Черновик<"),
    (">Auction type<", ">Тип аукциона<"),
    ('value="Reverse auction"', 'value="Обратный аукцион"'),
    ('placeholder="Describe lots and terms"', 'placeholder="Опишите лоты и условия"'),
    ('"Creating..."', '"Создание..."'),
    ('"Reset form"', '"Сбросить форму"'),
    ('"Go to sign in"', '"Перейти ко входу"'),
    ('"Create account"', '"Создать аккаунт"'),
    ('"Access your auctions and bids."', '"Доступ к вашим аукционам и ставкам."'),
    ('"Register as supplier, buyer or admin."', '"Регистрация как поставщик, заказчик или администратор."'),
    (">Register<", ">Регистрация<"),
    (">Username<", ">Имя пользователя<"),
    (">Password<", ">Пароль<"),
    ('"Signing in..."', '"Вход..."'),
    ('"Role"', '"Роль"'),
    (">Buyer<", ">Заказчик<"),
    (">Admin<", ">Администратор<"),
    ('"Company"', '"Компания"'),
    ('"Tax number"', '"ИНН"'),
    ('"My account"', '"Мой аккаунт"'),
    ('"Personal page with stats and auction shortcuts."', '"Личная страница с данными аккаунта и аукционами."'),
    ("<span>Username</span>", "<span>Имя пользователя</span>"),
    ("<span>Email</span>", "<span>Почта</span>"),
    ('<span>Role</span><strong>{currentUser?.profile?.role ?? "-"}</strong>', '<span>Роль</span><strong>{roleText(currentUser?.profile?.role ?? "-")}</strong>'),
    ("<span>Company</span>", "<span>Компания</span>"),
    ("<span>Tax number</span>", "<span>ИНН</span>"),
    ("<span>Rating</span>", "<span>Рейтинг</span>"),
    ("<span>Account ID</span>", "<span>ID аккаунта</span>"),
    ('<span>Signed in</span><strong>{tokens?.access ? "Yes" : "No"}</strong>', '<span>Вход выполнен</span><strong>{tokens?.access ? "Да" : "Нет"}</strong>'),
    ("<span>My auctions</span>", "<span>Мои аукционы</span>"),
    ("<span>Participating</span>", "<span>Участвует</span>"),
    ('"Loading account details..."', '"Загрузка данных аккаунта..."'),
    ('"Signed out."', '"Выход выполнен."'),
    ('"Sign out"', '"Выйти"'),
    ('"Edit account"', '"Редактирование аккаунта"'),
    ('"Update your account details. Email is read-only."', '"Измените данные аккаунта. Почта доступна только для чтения."'),
    ('"Sign in to edit your account."', '"Войдите, чтобы редактировать аккаунт."'),
    ('"Email (read-only)"', '"Почта (только чтение)"'),
    ('"New password (optional)"', '"Новый пароль (необязательно)"'),
    ('placeholder="Leave empty to keep current password"', 'placeholder="Оставьте пустым, чтобы не менять пароль"'),
    ('"Save changes"', '"Сохранить изменения"'),
    ('"Reset"', '"Сброс"'),
    ('"My auction listings"', '"Мои объявления"'),
    ('"Your auctions"', '"Ваши аукционы"'),
    ('"Sign in to see your auctions."', '"Войдите, чтобы посмотреть свои аукционы."'),
    ('"No auctions owned by this account yet."', '"У этого аккаунта пока нет созданных аукционов."'),
    ('label: "Edit"', 'label: "Редактировать"'),
    ('"Auctions I participate in"', '"Аукционы, в которых я участвую"'),
    ('"Auctions where you placed bids"', '"Аукционы, где вы сделали ставки"'),
    ('"Sign in to see participating auctions."', '"Войдите, чтобы посмотреть аукционы, в которых вы участвуете."'),
    ('"No participating auctions yet."', '"Пока нет аукционов, в которых вы участвуете."'),
]


def corrupt_variant(text: str) -> str:
    return "".join(ch if ord(ch) < 128 else "?" for ch in text)


def apply_replacements(content: str) -> str:
    for old, new in REPLACEMENTS:
        content = content.replace(old, new)
        content = content.replace(corrupt_variant(new), new)
    return content


def main() -> None:
    app = APP_PATH.read_text(encoding="utf-8", errors="replace")
    app = apply_replacements(app)
    APP_PATH.write_text(app, encoding="utf-8")

    api = API_PATH.read_text(encoding="utf-8", errors="replace")
    for old, new in [
        ("Unexpected server response", "Неверный ответ сервера"),
        ("???????? ????? ???????", "Неверный ответ сервера"),
    ]:
        api = api.replace(old, new)
    API_PATH.write_text(api, encoding="utf-8")

    print("ok")


if __name__ == "__main__":
    main()
